"""add guest_email to shared_access

Revision ID: 6b7d54707e6a
Revises: b560e0700f8b
Create Date: 2026-05-13 11:56:32.269758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7d54707e6a'
down_revision = 'b560e0700f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('authors', schema=None) as batch_op:
        # batch_op.alter_column('password_hash',
               # existing_type=sa.VARCHAR(length=256),
               # type_=sa.String(length=200),
               # existing_nullable=True)
        # batch_op.create_unique_constraint(batch_op.f('uq_authors_email'), ['email'])
        # batch_op.create_unique_constraint(batch_op.f('uq_authors_google_id'), ['google_id'])
        # batch_op.create_unique_constraint(batch_op.f('uq_authors_secret_token'), ['secret_token'])

    with op.batch_alter_table('shared_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        # batch_op.create_unique_constraint(batch_op.f('uq_shared_access_guest_token'), ['guest_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_access', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_shared_access_guest_token'), type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('guest_email')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_authors_secret_token'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_authors_google_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_authors_email'), type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
